"""Lockfile -> /etc/portage. Pure, deterministic, no model involved.

Rendering the same lockfile twice produces byte-identical files. Every line
carries the provenance that put it there, so `grep` on a live machine answers
"why is this flag set" without consulting the agent that decided it.
"""

from __future__ import annotations

from pathlib import Path

HEADER = """\
# Generated by forge from {lock_path}
# lock digest: {digest}
# DO NOT EDIT — edit aios.toml and re-run `forge lower && forge render`.
"""


def render(lock: dict, root: str | Path, *, lock_path: str = "aios.lock.json",
           overlay: str | Path | None = None) -> list[Path]:
    """Write the portage tree under `root`. Returns the files written."""
    root = Path(root)
    etc = root / "etc" / "portage"
    header = HEADER.format(lock_path=lock_path, digest=lock.get("digest", "unstamped"))
    written: list[Path] = []

    written.append(_write(etc / "make.conf", header + _make_conf(lock)))

    use = _package_use(lock)
    if use:
        written.append(_write(etc / "package.use" / "aios", header + use))

    keywords = _accept_keywords(lock)
    if keywords:
        written.append(_write(etc / "package.accept_keywords" / "aios", header + keywords))

    written.append(_write(etc / "sets" / "aios", header + _set_file(lock)))

    if overlay is not None:
        written.append(_write(etc / "repos.conf" / "aios.conf", header + _repos_conf(overlay)))

    return written


def _write(path: Path, body: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")
    return path


def _make_conf(lock: dict) -> str:
    lines = ["\n# --- build policy ---"]
    for entry in lock["make_conf"]:
        lines.append(f"# {entry['why']}")
        lines.append(f'{entry["key"]}="{entry["value"]}"')
        lines.append("")
    system = lock["system"]
    lines += [
        "# --- target ---",
        f'# {system["arch"]}/{system["libc"]}, init={system["init"]}, profile={system["profile"]}',
        "# The aios overlay is configured in repos.conf/aios.conf, not here —",
        "# PORTDIR_OVERLAY is deprecated and warns on every emerge.",
        "",
    ]
    return "\n".join(lines)


def _package_use(lock: dict) -> str:
    blocks: list[str] = []
    for pkg in lock["packages"]:
        if not pkg["use"]:
            continue
        atom = pkg["atom"]
        width = max(len(f["flag"]) for f in pkg["use"]) + 1
        lines = [f"\n# {atom} — {pkg['why']}"]
        for flag in pkg["use"]:
            token = f"{'+' if flag['enabled'] else '-'}{flag['flag']}"
            lines.append(f"#   {token:<{width}}  {flag['why']}")
        flags = " ".join(
            f["flag"] if f["enabled"] else f"-{f['flag']}" for f in pkg["use"]
        )
        lines.append(f"{atom} {flags}")
        blocks.append("\n".join(lines))
    return "\n".join(blocks) + "\n" if blocks else ""


def _accept_keywords(lock: dict) -> str:
    lines: list[str] = []
    for pkg in lock["packages"]:
        for keyword in pkg["accept_keywords"]:
            lines.append(f"# {pkg['why']}")
            lines.append(f"{pkg['atom']} {keyword}")
    return "\n" + "\n".join(lines) + "\n" if lines else ""


def _set_file(lock: dict) -> str:
    lines = ["\n# @aios — everything an intent asked for"]
    lines += [pkg["atom"] for pkg in lock["packages"]]
    return "\n".join(lines) + "\n"


def _repos_conf(overlay: str | Path) -> str:
    return (
        "\n[aios]\n"
        f"location = {overlay}\n"
        "masters = gentoo\n"
        "auto-sync = no\n"
        "priority = 100\n"
    )


def emerge_argv(lock: dict, *, root: str | Path = "/", pretend: bool = False,
                atoms: list[str] | None = None, binhost: bool = False,
                deep: bool = True, oneshot: bool = False) -> list[str]:
    """The emerge invocation for this lockfile.

    `--deep --newuse` is what makes a USE-flag change in the lock actually take
    effect; without it a rebuild silently keeps the previously built features.

    `binhost=True` lets this build consume binary packages another machine
    already compiled (see `binhost_env`). It changes only where object code
    comes from, never what gets built: portage still resolves the graph from the
    rendered lockfile, and rejects any binpkg whose USE flags disagree with it.

    `deep=False, oneshot=True` is the minimizer's shape. It rebuilds ONE atom, once
    per lever, dozens of times — and `--deep` re-resolves the entire dependency graph
    on every one of those, which is pure waste when only that atom's USE changed.
    `--changed-use` still catches the flag flip, which is the only thing that moved.
    `--oneshot` keeps the atom out of @world, so a minimization run does not rewrite
    the world file dozens of times as a side effect of measuring.
    """
    argv = ["emerge", "--verbose", "--newuse", "--changed-use"]
    if deep:
        argv.insert(2, "--deep")
    if oneshot:
        argv.append("--oneshot")
    if binhost:
        # --usepkg alone would accept only LOCAL binpkgs; --getbinpkg is what
        # reaches the remote host. Both, so a peer's cache and this machine's
        # own `buildpkg` output are equally usable.
        #
        # --binpkg-respect-use=y is the load-bearing one: it makes portage REJECT a
        # prebuilt package whose USE flags disagree with what the lockfile asked for,
        # and build from source instead. Without it, reusing a peer's binary silently
        # discards the feature decisions that are this project's entire point — a
        # peer's vim with +X would install over an intent that says no X11.
        argv += ["--getbinpkg", "--usepkg", "--binpkg-respect-use=y"]
    if str(root) != "/":
        argv.append(f"--root={root}")
    if pretend:
        argv.append("--pretend")
    argv += atoms if atoms else ["@aios"]
    return argv


def binhost_env(url: str, token: str | None = None) -> dict[str, str]:
    """Environment that points portage at a peer's binary package cache.

    Deliberately environment and NOT make.conf: which machines happen to be on
    the network is a fact about this moment, not about the machine being built.
    Putting it in the lockfile would make two nodes with identical specs render
    different portage trees and break the guarantee the lockfile exists to make.

    The token rides in the URL because portage fetches a binhost with wget/curl,
    which speak `http://user:pass@host/` but cannot add an auth header from
    PORTAGE_BINHOST.
    """
    if token:
        scheme, _, rest = url.partition("://")
        url = f"{scheme}://portage:{token}@{rest}"
    return {
        "PORTAGE_BINHOST": url,
        # stage3 ships no binpkg signing keys and these caches are peers on a
        # token-gated LAN, not a public mirror; without this portage refuses
        # every unsigned package it is offered.
        "FEATURES": "-binpkg-request-signature",
    }
