"""Lockfile -> /etc/portage. Pure, deterministic, no model involved.

Rendering the same lockfile twice produces byte-identical files. Every line
carries the provenance that put it there, so `grep` on a live machine answers
"why is this flag set" without consulting the agent that decided it.
"""

from __future__ import annotations

import re
from collections.abc import Iterable
from pathlib import Path

#: distccd's registered port. A `HOST/LIMIT` entry names no port, which means this
#: one — so it is the assumption every entry `distcc_host` renders carries, and the
#: thing to check when a distributed build silently compiles everything locally.
DISTCC_PORT = 3632

#: A DISTCC_HOSTS entry is not just a name. distcc's grammar reads a leading `@` as
#: "ssh to this host", and `HOST:COMMAND` as "and run COMMAND there" — so an
#: unvalidated peer name can direct this machine's preprocessed source anywhere. A
#: hostname, an IPv4 literal or a `host:port` is all a mesh peer may ever be.
DISTCC_HOST_RE = re.compile(r"^[A-Za-z0-9._:-]+$")

#: A make.conf line is `KEY="VALUE"`, so both halves are constrained by the shape of
#: that line and not by taste. A key that is not a bare variable name, or a value
#: carrying the quote that ends the assignment, does not describe one variable — it
#: describes two, and the second is whatever wrote it. `forge.lock.FORBIDDEN`
#: refuses PORTAGE_BINHOST and DISTCC_HOSTS by name; that refusal buys nothing if
#: either can ride in through an allowed entry's value.
MAKE_CONF_KEY = re.compile(r"^[A-Z][A-Z0-9_]*$")

#: Characters a value may not contain, because `KEY="VALUE"` cannot represent them.
#: `$` is deliberately absent: `CXXFLAGS="${CFLAGS}"` is an entry this renderer
#: itself writes and portage expands it. Whether a *model* may propose a `$` is a
#: different question, and it is answered at the agent boundary in `forge.lower`.
MAKE_CONF_UNQUOTABLE = '"\\\n\r'

#: What replaces a credential in anything human-visible. Never a partial value — a
#: prefix of a token is still a fact about the token.
REDACTION = "***"

_USERINFO = re.compile(r"(?<=://)[^/@\s]+@")

HEADER = """\
# Generated by forge from {lock_path}
# lock digest: {digest}
# DO NOT EDIT — edit aios.toml and re-run `forge lower && forge render`.
"""


class RenderError(Exception):
    """The lockfile carries something that cannot be written to /etc/portage."""


def render(lock: dict, root: str | Path, *, lock_path: str = "aios.lock.json",
           overlay: str | Path | None = None) -> list[Path]:
    """Write the portage tree under `root`. Returns the files written."""
    root = Path(root)
    etc = root / "etc" / "portage"
    header = HEADER.format(lock_path=lock_path, digest=lock.get("digest", "unstamped"))
    written: list[Path] = []

    written.append(_write(etc / "make.conf", header + _make_conf(lock)))

    use = _package_use(lock)
    if use:
        written.append(_write(etc / "package.use" / "aios", header + use))

    keywords = _accept_keywords(lock)
    if keywords:
        written.append(_write(etc / "package.accept_keywords" / "aios", header + keywords))

    written.append(_write(etc / "sets" / "aios", header + _set_file(lock)))

    if overlay is not None:
        written.append(_write(etc / "repos.conf" / "aios.conf", header + _repos_conf(overlay)))

    return written


def _write(path: Path, body: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")
    return path


def make_conf_reason(key: str, value: str, why: str = "") -> str:
    """Why this entry cannot be written as a make.conf assignment, or "" if it can.

    A reason rather than an exception because the two callers want different
    failures out of the same rule: `forge.lower` rejects the model's answer before
    it becomes an artifact, `_make_conf` refuses to render a lockfile that already
    carries one. All three fields are checked, because all three are interpolated
    into the file — a newline in `why` walks out of its `#` comment and onto a line
    portage obeys, which is the same defect as a quote in `value`.
    """
    if not MAKE_CONF_KEY.match(key):
        return f"key {key!r} is not a make.conf variable name ([A-Z][A-Z0-9_]*)"
    bad = sorted({char for char in value if char in MAKE_CONF_UNQUOTABLE})
    if bad:
        return (
            f"value for {key} contains {', '.join(repr(c) for c in bad)}, which ends "
            f'the {key}="…" assignment and starts another'
        )
    if "\n" in why or "\r" in why:
        return f"the `why` for {key} contains a newline, which ends its comment line"
    return ""


def _make_conf(lock: dict) -> str:
    lines = ["\n# --- build policy ---"]
    for entry in lock["make_conf"]:
        # Second line of defence, and the only one a hand-edited lock still meets:
        # `forge.lower` rejects this at the agent boundary, but `render` reads the
        # lockfile, not the lowering, and an unrenderable lock must stop here rather
        # than become a /etc/portage that says more than the lockfile does.
        reason = make_conf_reason(str(entry["key"]), str(entry["value"]), str(entry["why"]))
        if reason:
            raise RenderError(f"refusing to render make.conf: {reason}")
        lines.append(f"# {entry['why']}")
        lines.append(f'{entry["key"]}="{entry["value"]}"')
        lines.append("")
    system = lock["system"]
    lines += [
        "# --- target ---",
        f'# {system["arch"]}/{system["libc"]}, init={system["init"]}, profile={system["profile"]}',
        "# The aios overlay is configured in repos.conf/aios.conf, not here —",
        "# PORTDIR_OVERLAY is deprecated and warns on every emerge.",
        "",
    ]
    return "\n".join(lines)


def _package_use(lock: dict) -> str:
    blocks: list[str] = []
    for pkg in lock["packages"]:
        if not pkg["use"]:
            continue
        atom = pkg["atom"]
        width = max(len(f["flag"]) for f in pkg["use"]) + 1
        lines = [f"\n# {atom} — {pkg['why']}"]
        for flag in pkg["use"]:
            token = f"{'+' if flag['enabled'] else '-'}{flag['flag']}"
            lines.append(f"#   {token:<{width}}  {flag['why']}")
        flags = " ".join(
            f["flag"] if f["enabled"] else f"-{f['flag']}" for f in pkg["use"]
        )
        lines.append(f"{atom} {flags}")
        blocks.append("\n".join(lines))
    return "\n".join(blocks) + "\n" if blocks else ""


def _accept_keywords(lock: dict) -> str:
    lines: list[str] = []
    for pkg in lock["packages"]:
        for keyword in pkg["accept_keywords"]:
            lines.append(f"# {pkg['why']}")
            lines.append(f"{pkg['atom']} {keyword}")
    return "\n" + "\n".join(lines) + "\n" if lines else ""


def _set_file(lock: dict) -> str:
    lines = ["\n# @aios — everything an intent asked for"]
    lines += [pkg["atom"] for pkg in lock["packages"]]
    return "\n".join(lines) + "\n"


def _repos_conf(overlay: str | Path) -> str:
    return (
        "\n[aios]\n"
        f"location = {overlay}\n"
        "masters = gentoo\n"
        "auto-sync = no\n"
        "priority = 100\n"
    )


def emerge_argv(lock: dict, *, root: str | Path = "/", pretend: bool = False,
                atoms: list[str] | None = None, binhost: bool = False,
                deep: bool = True, oneshot: bool = False) -> list[str]:
    """The emerge invocation for this lockfile.

    `--deep --newuse` is what makes a USE-flag change in the lock actually take
    effect; without it a rebuild silently keeps the previously built features.

    `binhost=True` lets this build consume binary packages another machine
    already compiled (see `binhost_env`). It changes only where object code
    comes from, never what gets built: portage still resolves the graph from the
    rendered lockfile, and rejects any binpkg whose USE flags disagree with it.

    `deep=False, oneshot=True` is the minimizer's shape. It rebuilds ONE atom, once
    per lever, dozens of times — and `--deep` re-resolves the entire dependency graph
    on every one of those, which is pure waste when only that atom's USE changed.
    `--changed-use` still catches the flag flip, which is the only thing that moved.
    `--oneshot` keeps the atom out of @world, so a minimization run does not rewrite
    the world file dozens of times as a side effect of measuring.
    """
    argv = ["emerge", "--verbose", "--newuse", "--changed-use"]
    if deep:
        argv.insert(2, "--deep")
    if oneshot:
        argv.append("--oneshot")
    if binhost:
        # --usepkg alone would accept only LOCAL binpkgs; --getbinpkg is what
        # reaches the remote host. Both, so a peer's cache and this machine's
        # own `buildpkg` output are equally usable.
        #
        # --binpkg-respect-use=y is the load-bearing one: it makes portage REJECT a
        # prebuilt package whose USE flags disagree with what the lockfile asked for,
        # and build from source instead. Without it, reusing a peer's binary silently
        # discards the feature decisions that are this project's entire point — a
        # peer's vim with +X would install over an intent that says no X11.
        argv += ["--getbinpkg", "--usepkg", "--binpkg-respect-use=y"]
    if str(root) != "/":
        argv.append(f"--root={root}")
    if pretend:
        argv.append("--pretend")
    argv += atoms if atoms else ["@aios"]
    return argv


def binhost_env(url: str, token: str | None = None) -> dict[str, str]:
    """Environment that points portage at a peer's binary package cache.

    Deliberately environment and NOT make.conf: which machines happen to be on
    the network is a fact about this moment, not about the machine being built.
    Putting it in the lockfile would make two nodes with identical specs render
    different portage trees and break the guarantee the lockfile exists to make.

    The token rides in the URL because portage fetches a binhost with wget/curl,
    which speak `http://user:pass@host/` but cannot add an auth header from
    PORTAGE_BINHOST.
    """
    if token:
        scheme, _, rest = url.partition("://")
        url = f"{scheme}://portage:{token}@{rest}"
    return {
        "PORTAGE_BINHOST": url,
        # stage3 ships no binpkg signing keys and these caches are peers on a
        # token-gated LAN, not a public mirror; without this portage refuses
        # every unsigned package it is offered.
        "FEATURES": "-binpkg-request-signature",
        # Waiving the signature REQUIREMENT is not enough on its own. Before any
        # binpkg operation portage runs PORTAGE_TRUST_HELPER, which defaults to
        # `getuto` — the tool that builds the OpenPGP trust anchor for verifying
        # them. On a stage3 with no keyring it does not fail, it HANGS: measured
        # here at 14 minutes still in do_wait on a getuto child with zero CPU,
        # producing not one byte of output, on an emerge of seven cached binary
        # packages that otherwise takes seconds. Worse, it holds portage's lock,
        # so every later emerge in the node blocks silently behind it and looks
        # like the network is slow. There is nothing to verify — we just waived
        # verification one line up — so the helper has no work to do here.
        "PORTAGE_TRUST_HELPER": "/bin/true",
    }


def distcc_host(host: str, jobs: int, port: int | None = None) -> str:
    """One `DISTCC_HOSTS` entry: `HOST/LIMIT`, or `HOST:PORT/LIMIT` with a port.

    LIMIT is clamped to at least 1 because distcc rejects the WHOLE host list when
    one entry is malformed. A peer that advertises zero cores — a share daemon that
    could not count them — would otherwise cost this build every other peer too.

    PORT is written only when it is not distcc's default, so the common entry stays
    the familiar `host/8`. It is range-checked rather than trusted: the number comes
    from another machine's JSON, and a peer that publishes distccd on a non-default
    port is a supported configuration (`builderDistccPort`), not an anomaly.

    HOST is validated rather than trusted, and raises: the name reaching here comes
    from another machine's JSON, while a DISTCC_HOSTS entry is a small language.
    `@name` means "ssh there", `name:COMMAND` means "and run this", and a `"` breaks
    out of the shell line `aios.mesh` prints for `eval`. A peer that could name
    itself could otherwise choose where this machine's source code goes.
    """
    if not DISTCC_HOST_RE.match(host):
        raise ValueError(f"{host!r} is not a distcc host name")
    limit = max(1, int(jobs))
    if port is None or int(port) == DISTCC_PORT:
        return f"{host}/{limit}"
    if not 1 <= int(port) <= 65535:
        raise ValueError(f"{port!r} is not a port")
    return f"{host}:{int(port)}/{limit}"


def redact_url(url: str) -> str:
    """A URL as a human may see it: userinfo replaced, everything else intact.

    The inverse of the one line in `binhost_env` that puts a credential into a URL,
    and it lives beside it for that reason. `forge build --peer` is handed exactly
    what `aios.mesh.binhost_url()` returns — a URL whose own docstring says it is
    UNREDACTED — so the print next to it must be the redacting one.
    `aios.mesh.scrub` is the same rule over arbitrary text and delegates here.
    """
    return _USERINFO.sub(f"x:{REDACTION}@", url)


def distcc_env(hosts: Iterable[str]) -> dict[str, str]:
    """Environment that offers portage a set of machines to compile ON.

    The same rule as `binhost_env`, one level down: a binhost shares packages that
    are already built, distcc shares the individual compile jobs that build them,
    and both are facts about which machines happen to be up right now rather than
    about the machine being described. Two nodes with identical specs must render
    identical portage trees, so neither key may enter the lockfile — `forge.lock`
    refuses both by name — and neither is ever written into make.conf.

    What is spec-owned instead is `FEATURES="distcc"` (aios.toml `system.features`),
    because whether this machine routes its compiles through distcc at all is part
    of what it IS. This function only says who it can reach.

    An EMPTY host list is the normal case, not an error. DISTCC_HOSTS is exported
    empty, distcc finds nobody to send the job to, and DISTCC_FALLBACK makes it run
    the local compiler: a working build, just not a faster one. Exporting it empty
    rather than leaving it unset is the point — unset, distcc reads
    /etc/distcc/hosts, and what a build did would depend on a file nothing in this
    pipeline renders.
    """
    return {
        "DISTCC_HOSTS": " ".join(hosts),
        # Stated rather than left to distcc's default, because the empty-list case
        # rests on it: with no usable host, compile locally instead of failing.
        "DISTCC_FALLBACK": "1",
    }
